### ISSUE TITLE
custom dataset

### ISSUE THREAD

**Issue by ghost** [qmdnls/ADM19F-bot-detection#1]
Hi,

Hope you are all well !

How to create a custom dataset ? Is there a script ?

Cheers,
X

**Comment by nagmat1** [comment]
Hi, 

Thank you very much. We didn't use a script while creating custom dataset. 
https://github.com/qmdnls/ADM19F-bot-detection/blob/master/scraping/get_all_profiles.py

Kind regards, 
N
