### ISSUE TITLE
about the dataset

### ISSUE THREAD

**Issue by hy1712** [qmdnls/ADM19F-bot-detection#2]
Can you share profile data of all users followed by and following users in the dataset?

**Comment by qmdnls** [comment]
Sorry, as per the Twitter developer policy it is not allowed for us to share profile data that we have collected directly. However, we have shared the script used to collect the IDs of users followed by and following users in the dataset. It should be easy for you to use this script or a modified version of it to similarly collect all users followed by and following users in a dataset using your own Twitter API key.
See: https://github.com/qmdnls/ADM19F-bot-detection/blob/master/scraping/get_following.py
